default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: SAP_development

test:
  <<: *default
  database: SAP_test

production:
  <<: *default
  database: SAP_production
  username: postgres
  password: postgres